# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(561, 438)
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(30, 110, 511, 261))
        self.tableView.setObjectName("tableView")

        # สร้าง model
        self.model = QtGui.QStandardItemModel()

        # ตั้งค่าคอลัมน์ (Header)
        self.model.setHorizontalHeaderLabels(["plant_ID", "Name", "Type","age"])

        # # ใส่ข้อมูลในแต่ละเซลล์
        # for row in range(5):  # สร้าง 5 แถว
        #     for column in range(3):  # สร้าง 3 คอลัมน์
        #         item = QtGui.QStandardItem(f"Data {row + 1}, {column + 1}")
        #         self.model.setItem(row, column, item)

        # ตั้ง model ให้กับ QTableView
        self.tableView.setModel(self.model)

        self.label = QtWidgets.QLabel(Form);self.label.setGeometry(QtCore.QRect(30, 80, 58, 16));self.label.setObjectName("label")
        #Button
        self.Add_data_Button = QtWidgets.QPushButton(Form);self.Add_data_Button.setGeometry(QtCore.QRect(30, 380, 111, 51));self.Add_data_Button.setObjectName("Add_data_Button")
        self.Add_data_Button.setStyleSheet("""
                    QPushButton {
                        background-color: blue; /* Red background */
                        color: white;          /* White text */
                        border: none;
                        font-weight: bold;
                    }
                    QPushButton:hover {
                        background-color: darkblue; /* Dark red on hover */
                    }
                """)
        self.Dell_Button = QtWidgets.QPushButton(Form);self.Dell_Button.setGeometry(QtCore.QRect(420, 380, 111, 51));self.Dell_Button.setObjectName("Dell_Button")
        self.Dell_Button.setStyleSheet("""
            QPushButton {
                background-color: red; /* Red background */
                color: white;          /* White text */
                border: none;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: darkred; /* Dark red on hover */
            }
        """)
        self.data_Button = QtWidgets.QPushButton(Form);self.data_Button.setGeometry(QtCore.QRect(160, 380, 111, 51));self.data_Button.setObjectName("data_Button")
        self.seach_Button = QtWidgets.QPushButton(Form);self.seach_Button.setGeometry(QtCore.QRect(430, 60, 111, 51));self.seach_Button.setObjectName("data_Button_2")
        self.reload_Button = QtWidgets.QPushButton(Form);self.reload_Button.setGeometry(QtCore.QRect(290, 380, 111, 51));self.reload_Button.setObjectName("data_Button_3")
        self.textEdit = QtWidgets.QTextEdit(Form);self.textEdit.setGeometry(QtCore.QRect(90, 70, 321, 31));self.textEdit.setObjectName("textEdit")
        #label
        self.label_2 = QtWidgets.QLabel(Form);self.label_2.setGeometry(QtCore.QRect(180, 20, 161, 41));self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "plant id"))
        self.Add_data_Button.setText(_translate("Form", "add data"))
        self.Dell_Button.setText(_translate("Form", "Dell"))
        self.data_Button.setText(_translate("Form", "Show Data"))
        self.seach_Button.setText(_translate("Form", "seach"))
        self.reload_Button.setText(_translate("Form", "Reload"))
        self.label_2.setText(_translate("Form", "DATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
