# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'docter_plant_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1049, 394)
        # self.radioButton = QtWidgets.QRadioButton(Form)
        # self.radioButton.setGeometry(QtCore.QRect(230, 60, 99, 20))
        # self.radioButton.setObjectName("radioButton")
        # self.radioButton_2 = QtWidgets.QRadioButton(Form)
        # self.radioButton_2.setGeometry(QtCore.QRect(370, 60, 99, 20))
        # self.radioButton_2.setObjectName("radioButton_2")
        # self.radioButton_3 = QtWidgets.QRadioButton(Form)
        # self.radioButton_3.setGeometry(QtCore.QRect(530, 60, 99, 20))
        # self.radioButton_3.setObjectName("radioButton_3")
        self.textEdit_plant = QtWidgets.QTextEdit(Form)
        self.textEdit_plant.setGeometry(QtCore.QRect(490, 10, 71, 21))
        self.textEdit_plant.setObjectName("label")
        self.textEdit_plant.setReadOnly(True)

        # self.pushButton = QtWidgets.QPushButton(Form)
        # self.pushButton.setGeometry(QtCore.QRect(680, 50, 131, 41))
        # self.pushButton.setObjectName("pushButton")

        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(20, 101, 1011, 201))
        self.tableView.setObjectName("tableView")



        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 320, 101, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 320, 101, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(560, 320, 101, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(710, 320, 101, 51))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

        # self.radioButton.setText(_translate("Form", "มะม่วง"))
        # self.radioButton_2.setText(_translate("Form", "ทุเรียน"))
        # self.radioButton_3.setText(_translate("Form", "มังคุด"))

        self.textEdit_plant.setText(_translate("Form", "plant type"))
        # self.pushButton.setText(_translate("Form", "OK"))
        self.pushButton_2.setText(_translate("Form", "1"))
        self.pushButton_3.setText(_translate("Form", "2"))
        self.pushButton_4.setText(_translate("Form", "3"))
        self.pushButton_5.setText(_translate("Form", "4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
