# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("GreenGrow Advisor")
        Form.resize(500, 554)
        #label
        self.label_UV_index = QtWidgets.QLabel(Form);self.label_UV_index.setGeometry(QtCore.QRect(40, 40, 108, 16));self.label_UV_index.setObjectName("label_UV_index")
        self.label_Temperature = QtWidgets.QLabel(Form);self.label_Temperature.setGeometry(QtCore.QRect(40, 80, 108, 16));self.label_Temperature.setObjectName("label_Temperature")
        self.label_Humidity = QtWidgets.QLabel(Form);self.label_Humidity.setGeometry(QtCore.QRect(40, 120, 108, 16));self.label_Humidity.setObjectName("label_Humidity")
        self.label_Precipitation_Q1 = QtWidgets.QLabel(Form);self.label_Precipitation_Q1.setGeometry(QtCore.QRect(40, 160, 108, 16));self.label_Precipitation_Q1.setObjectName("label_Precipitation_Q1")
        self.label_Precipitation_Q2 = QtWidgets.QLabel(Form);self.label_Precipitation_Q2.setGeometry(QtCore.QRect(40, 200, 108, 16));self.label_Precipitation_Q2.setObjectName("label_Precipitation_Q2")
        self.label_Precipitation_Q3 = QtWidgets.QLabel(Form);self.label_Precipitation_Q3.setGeometry(QtCore.QRect(40, 240, 108, 16));self.label_Precipitation_Q3.setObjectName("label_Precipitation_Q3")
        self.label_Precipitation_Q4 = QtWidgets.QLabel(Form);self.label_Precipitation_Q4.setGeometry(QtCore.QRect(40, 280, 108, 16));self.label_Precipitation_Q4.setObjectName("label_Precipitation_Q4")
        self.label_Nitrogen = QtWidgets.QLabel(Form);self.label_Nitrogen.setGeometry(QtCore.QRect(40, 320, 108, 16));self.label_Nitrogen.setObjectName("label_Nitrogen")
        self.label_Phosphorus = QtWidgets.QLabel(Form);self.label_Phosphorus.setGeometry(QtCore.QRect(40, 360, 108, 16));self.label_Phosphorus.setObjectName("label_Phosphorus")
        self.label_Potassium = QtWidgets.QLabel(Form);self.label_Potassium.setGeometry(QtCore.QRect(40, 400, 108, 16));self.label_Potassium.setObjectName("label_Potassium")
        self.label_ANS = QtWidgets.QLabel(Form);self.label_ANS.setGeometry(QtCore.QRect(200, 440, 241, 20));self.label_ANS.setObjectName("label_ANS")
        #Button
        self.pushButton_cal = QtWidgets.QPushButton(Form);self.pushButton_cal.setGeometry(QtCore.QRect(360, 30, 121, 61));self.pushButton_cal.setObjectName("pushButton_cal")
        self.pushButton_cal.setStyleSheet("""QPushButton {background-color: blue;color: white;border: none;font-weight: bold;}QPushButton:hover {background-color: darkblue; }""")
        self.pushButton_cls = QtWidgets.QPushButton(Form);self.pushButton_cls.setGeometry(QtCore.QRect(360, 100, 121, 61));self.pushButton_cls.setObjectName("pushButton_cls")
        self.pushButton_data = QtWidgets.QPushButton(Form);self.pushButton_data.setGeometry(QtCore.QRect(360, 170, 121, 61));self.pushButton_data.setObjectName("pushButton_data")
        #textEdit
        self.textEdit_UV_index = QtWidgets.QTextEdit(Form);self.textEdit_UV_index.setGeometry(QtCore.QRect(180, 40, 121, 31));self.textEdit_UV_index.setObjectName("textEdit_UV_index")
        self.textEdit_Temperature = QtWidgets.QTextEdit(Form);self.textEdit_Temperature.setGeometry(QtCore.QRect(180, 80, 121, 31));self.textEdit_Temperature.setObjectName("textEdit_Temperature")
        self.textEdit_Humidity = QtWidgets.QTextEdit(Form);self.textEdit_Humidity.setGeometry(QtCore.QRect(180, 120, 121, 31));self.textEdit_Humidity.setObjectName("textEdit_Humidity")
        self.textEdit_Precipitation_Q1 = QtWidgets.QTextEdit(Form);self.textEdit_Precipitation_Q1.setGeometry(QtCore.QRect(180, 160, 121, 31));self.textEdit_Precipitation_Q1.setObjectName("textEdit_Precipitation_Q1")
        self.textEdit_Precipitation_Q2 = QtWidgets.QTextEdit(Form);self.textEdit_Precipitation_Q2.setGeometry(QtCore.QRect(180, 200, 121, 31));self.textEdit_Precipitation_Q2.setObjectName("textEdit_Precipitation_Q2")
        self.textEdit_Precipitation_Q3 = QtWidgets.QTextEdit(Form);self.textEdit_Precipitation_Q3.setGeometry(QtCore.QRect(180, 240, 121, 31));self.textEdit_Precipitation_Q3.setObjectName("textEdit_Precipitation_Q3")
        self.textEdit_Precipitation_Q4 = QtWidgets.QTextEdit(Form);self.textEdit_Precipitation_Q4.setGeometry(QtCore.QRect(180, 280, 121, 31));self.textEdit_Precipitation_Q4.setObjectName("textEdit_Precipitation_Q4")
        self.textEdit_Nitrogen = QtWidgets.QTextEdit(Form);self.textEdit_Nitrogen.setGeometry(QtCore.QRect(180, 320, 121, 31));self.textEdit_Nitrogen.setObjectName("textEdit_Nitrogen")
        self.textEdit_Phosphorus = QtWidgets.QTextEdit(Form);self.textEdit_Phosphorus.setGeometry(QtCore.QRect(180, 360, 121, 31));self.textEdit_Phosphorus.setObjectName("textEdit_Phosphorus")
        self.textEdit_Potassium = QtWidgets.QTextEdit(Form);self.textEdit_Potassium.setGeometry(QtCore.QRect(180, 400, 121, 31));self.textEdit_Potassium.setObjectName("textEdit_Potassium")
        self.textEdit_ANS = QtWidgets.QTextEdit(Form);self.textEdit_ANS.setGeometry(QtCore.QRect(300, 440, 121, 31));self.textEdit_ANS.setReadOnly(True);self.textEdit_ANS.setObjectName("textEdit_4")
        #form
        self.retranslateUi(Form);QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "GreenGrow Advisor"))
        # set label text
        self.label_UV_index.setText(_translate("Form", "UV_index:"))
        self.label_Temperature.setText(_translate("Form", "Temperature :"))
        self.label_ANS.setText(_translate("Form", "ANS:"))
        self.label_Humidity.setText(_translate("Form", "Humidity:"))
        self.label_Precipitation_Q1.setText(_translate("Form", "Precipitation_Q1:"))
        self.label_Precipitation_Q2.setText(_translate("Form", "Precipitation_Q2:"))
        self.label_Precipitation_Q3.setText(_translate("Form", "Precipitation_Q3:"))
        self.label_Precipitation_Q4.setText(_translate("Form", "Precipitation_Q4:"))
        self.label_Nitrogen.setText(_translate("Form", "Nitrogen:"))
        self.label_Phosphorus.setText(_translate("Form", "Phosphorus :"))
        self.label_Potassium.setText(_translate("Form", "Potassium:"))
        # set Button text
        self.pushButton_cal.setText(_translate("Form", "cal"))
        self.pushButton_cls.setText(_translate("Form", "cls"))
        self.pushButton_data.setText(_translate("Form", "data"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
